# A workflow to build and upload every 2 weeks
name: Linux

on:
  schedule:
    - cron: '0 0 * * 0/14'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux
    steps:
      - name: Install Dependencies
        run: |
          pacman -Syu --noconfirm --needed base-devel boost catch2 cmake ffmpeg fmt git glslang libzip lz4 mbedtls ninja nlohmann-json openssl opus qt5 sdl2 zlib zstd zip unzip

      - name: Git Checkout
        run: |
          git clone --depth 1 --recursive https://codeberg.org/litucks/torzu.git

      - name: Restore CCache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          max-size: 3Gi

      - name: Linux Assemble
        env:
          CMAKE_C_COMPILER_LAUNCHER: "ccache"
          CMAKE_CXX_COMPILER_LAUNCHER: "ccache"
        run: |
          cd torzu
          mkdir build && cd build
          cmake .. -GNinja -DYUZU_USE_BUNDLED_VCPKG=ON -DYUZU_TESTS=OFF
          ninja
      
      - name: Rename Binaries
        run: |
          mv torzu/build/bin/yuzu torzu-release-linux
      
      - name: Upload Release Binary
        uses: actions/upload-artifact@v4
        with:
          name: torzu-release-linux
          path: torzu-release-linux
